apiVersion: v1
kind: Service
metadata:
  name: dns
spec:
  # Used as upstream for coredns.
  clusterIP: 10.97.0.11
  ports:
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: dns-tcp
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: dns-udp
  selector:
    apps.zarantonello.dev/name: blocky
    apps.zarantonello.dev/namespace: blocky
  # Use same node since for now each one has a dns server. If we expand it would
  # be better to set zones.
  trafficDistribution: PreferSameNode
