apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fluxcd
resources:
  - https://github.com/fluxcd/source-controller/config/crd/?ref=v1.9.4
  - https://github.com/fluxcd/helm-controller/config/crd/?ref=v1.6.3
  - https://github.com/fluxcd/kustomize-controller/config/crd/?ref=v1.9.4
  - cluster-role-bindings/fluxcd-cluster-reconciler.yaml
  - cluster-role-bindings/fluxcd-crd-controller.yaml
  - cluster-roles/fluxcd-crd-controller.yaml
  - deployments/helm-controller.yaml
  - deployments/kustomize-controller.yaml
  - deployments/source-controller.yaml
  - kustomization.flux.yaml
  - namespace.yaml
  - service-accounts/default.yaml
  - service-accounts/helm-controller.yaml
  - service-accounts/kustomize-controller.yaml
  - service-accounts/source-controller.yaml
  - services/source-controller.yaml
