apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fluxcd
resources:
  # Get crds from flux's github repo.
  - https://github.com/fluxcd/flux2/manifests/crds/?ref=v2.7.1
  - cluster-role-bindings/fluxcd-cluster-reconciler.yaml
  - cluster-role-bindings/fluxcd-crd-controller.yaml
  - cluster-roles/fluxcd-crd-controller.yaml
  - deployments/helm-controller.yaml
  - deployments/kustomize-controller.yaml
  - deployments/source-controller.yaml
  - kustomization.flux.yaml
  - namespace.yaml
  - service-accounts/default.yaml
  - service-accounts/helm-controller.yaml
  - service-accounts/kustomize-controller.yaml
  - service-accounts/source-controller.yaml
  - services/source-controller.yaml
