apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: default
spec:
  hostnames:
    - photos.zarantonello.net
  parentRefs:
    - name: srv-home-tailscale-https
      namespace: cilium
    # App connects via http since it's lighter and encryption is provided by
    # Tailscale.
    - name: srv-home-tailscale-http
      namespace: cilium
  rules:
    - backendRefs:
        - name: server
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
