apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  diskSelector:
    match: disk.bus_path == "/pci0000:00/0000:00:01.2/0000:02:00.0/nvme"
  maxSize: 40GiB
  minSize: 40GiB
---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: data-0
provisioning:
  diskSelector:
    match: disk.bus_path == "/pci0000:00/0000:00:01.2/0000:02:00.0/nvme"
  grow: true
  minSize: 1GiB
