apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
spec:
  chart:
    spec:
      chart: cilium
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: cilium
      version: 1.18.1
  install:
    crds: Create
  interval: 5m
  releaseName: cilium
  upgrade:
    crds: Create
  values:
    bpf:
      datapathMode: netkit
      masquerade: true
    bpfClockProbe: true
    # Cgroup mount is already provided by talos, so we can reuse it.
    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup
    envoy:
      enabled: true
      podAnnotations:
        monitoring.zarantonello.dev/metrics-0-id: 838b2289-7eeb-4105-a505-d6b3cd0a413c
        monitoring.zarantonello.dev/metrics-0-port: "9964"
      prometheus:
        enabled: true
        port: "9964"
    gatewayAPI:
      enableAlpn: true
      enableAppProtocol: true
      enabled: true
    hostFirewall:
      enabled: true
    hubble:
      enabled: true
      metrics:
        enabled:
          - dns:sourceContext=reserved-identity;destinationContext=reserved-identity;labelsContext=source_ip,source_namespace,source_pod,destination_ip,destination_namespace,destination_pod,traffic_direction
          - drop:sourceContext=reserved-identity;destinationContext=reserved-identity;labelsContext=source_ip,source_namespace,source_pod,destination_ip,destination_namespace,destination_pod,traffic_direction
          - tcp:sourceContext=reserved-identity;destinationContext=reserved-identity;labelsContext=source_ip,source_namespace,source_pod,destination_ip,destination_namespace,destination_pod,traffic_direction
          - flow:sourceContext=reserved-identity;destinationContext=reserved-identity;labelsContext=source_ip,source_namespace,source_pod,destination_ip,destination_namespace,destination_pod,traffic_direction
          - flows-to-world:any-drop=true;port=true;sourceContext=reserved-identity;destinationContext=reserved-identity;labelsContext=source_ip,source_namespace,source_pod,destination_ip,destination_namespace,destination_pod,traffic_direction
          - port-distribution:sourceContext=reserved-identity;destinationContext=reserved-identity;labelsContext=source_ip,source_namespace,source_pod,destination_ip,destination_namespace,destination_pod,traffic_direction
          - icmp:sourceContext=reserved-identity;destinationContext=reserved-identity;labelsContext=source_ip,source_namespace,source_pod,destination_ip,destination_namespace,destination_pod,traffic_direction
          - httpV2:sourceContext=reserved-identity;destinationContext=reserved-identity;labelsContext=source_ip,source_namespace,source_pod,destination_ip,destination_namespace,destination_pod,traffic_direction
        port: 9965
      peerService:
        clusterDomain: k8s.zarantonello.dev
      relay:
        enabled: false
        nodeSelector:
          node-role.kubernetes.io/control-plane: ""
        podAnnotations:
          monitoring.zarantonello.dev/metrics-0-id: 28fc59f2-8a41-43a4-9f19-afaab1c4fd52
          monitoring.zarantonello.dev/metrics-0-port: "9966"
        prometheus:
          enabled: true
          port: 9966
      ui:
        enabled: false
        nodeSelector:
          node-role.kubernetes.io/control-plane: ""
    ipam:
      mode: kubernetes
    ipv4:
      enabled: true
    ipv6:
      enabled: true
    k8sServiceHost: 10.95.0.1
    k8sServicePort: 6443
    kubeProxyReplacement: true
    operator:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      podAnnotations:
        monitoring.zarantonello.dev/metrics-0-id: ea5aa09d-948c-4fa0-a576-7381be50c2b4
        monitoring.zarantonello.dev/metrics-0-port: "9963"
      prometheus:
        enabled: true
        port: 9963
      replicas: 1
    podAnnotations:
      monitoring.zarantonello.dev/metrics-0-id: ee101f49-f2ba-4c39-a45d-fa16f57615d5
      monitoring.zarantonello.dev/metrics-0-port: "9962"
      monitoring.zarantonello.dev/metrics-1-id: d747a514-5634-4c66-9016-e9f5d46154fa
      monitoring.zarantonello.dev/metrics-1-port: "9965"
    prometheus:
      enabled: true
      port: 9962
    # Talos doesn't allow creating pods with SYS_MODULE capability. We have to
    # override the default values for cilium-agent to remove it.
    securityContext:
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
