apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-dns-rs
spec:
  selector:
    matchLabels:
      apps.zarantonello.dev/name: kube-dns-rs
      apps.zarantonello.dev/namespace: kube-dns-rs
  template:
    metadata:
      labels:
        apps.zarantonello.dev/name: kube-dns-rs
        apps.zarantonello.dev/namespace: kube-dns-rs
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            # Avoid having multiple instances of the same pod in a single node.
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    apps.zarantonello.dev/name: kube-dns-rs
                    apps.zarantonello.dev/namespace: kube-dns-rs
                topologyKey: kubernetes.io/hostname
              weight: 50
      containers:
        - image: git.zarantonello.dev/projects/kube-dns-rs:v1.0.4@sha256:b9dd88f0d717ecd0a3c76dd539ab53730d5e9ead5183efe97b0109c8ef6dbabe
          name: kube-dns-rs
          ports:
            - containerPort: 1053
              name: dns-tcp
              protocol: TCP
            - containerPort: 1053
              name: dns-udp
              protocol: UDP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          startupProbe:
            tcpSocket:
              port: 1053
          volumeMounts:
            - mountPath: /etc/kube-dns-rs
              name: config
      dnsConfig:
        nameservers:
          - 1.1.1.1
          - 1.0.0.1
      dnsPolicy: None
      enableServiceLinks: false
      securityContext:
        runAsGroup: 3146
        runAsNonRoot: true
        runAsUser: 3146
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: kube-dns-rs
      volumes:
        - configMap:
            name: kube-dns-rs-config
          name: config
