cache:
  dir: /data/cache

container:
  options: --add-host git.zarantonello.dev:100.83.193.88
  privileged: true
  valid_volumes:
    - forgejo-runner-cache-*

host:
  workdir_parent: /data/job

log:
  job_level: info
  level: info

runner:
  capacity: 1
  fetch_interval: 5s
  shutdown_timeout: 2h
