[Qwen3.6-35B-A3B]
batch-size=1024
cache-ram=4096
chat-template-kwargs={"preserve_thinking":true}
ctk=q8_0
ctv=q8_0
ctx-size=65536
fit=off
min-p=0
mmap=false
model=/var/lib/llama-server/Qwen3.6-35B-A3B-UD-Q4_K_XL.gguf
presence-penalty=0.2
spec-type=draft-mtp,ngram-mod
temperature=0.6
top-k=20
top-p=0.95
ubatch-size=256

; [Gemma4-26B-A4B]
; ctx-size=65536
; ctk=q8_0
; ctv=q8_0
; model=/var/lib/llama-server/gemma-4-26B-A4B-it-qat-UD-Q4_K_XL.gguf
; model-draft=/var/lib/llama-server/gemma-4-26B-A4B-it-Q8_0-MTP.gguf
; spec-type=draft-mtp,ngram-mod
; temperature=1.0
; top-k=64
; top-p=0.95
