machine:
  install:
    disk: /dev/sda
    image: factory.talos.dev/metal-installer/708747e350d604ae9e57227d8dcf274091453ddb1097b765d4ea8884f1992c1f:v1.11.0
  kubelet:
    extraMounts:
      - destination: /var/mnt/longhorn-0
        options:
          - bind
          - rshared
          - rw
        source: /var/mnt/longhorn-0
        type: bind
  network:
    hostname: srv-0-fsk-hetz.servers.zarantonello.dev
    interfaces:
      - addresses:
          - 2a01:4f8:c013:315c::/64
        # Setting ipv4 and ipv6 gateways leads to only the ipv6 one being kept.
        # I have no idea why, so we just let dhcp handle ipv4.
        dhcp: true
        interface: enp1s0
        routes:
          - gateway: fe80::1
            network: ::/0
      - addresses:
          - 10.95.0.1/24
          - fda9:b00c:8b29:33f9::1095:1/120
        interface: wg0
        mtu: 1400
        wireguard:
          listenPort: 51000
          peers:
            # srv-0-cor-home
            - allowedIPs:
                - 10.95.0.2/32
                - fda9:b00c:8b29:33f9::1095:2/128
              endpoint: srv-0-cor-home.servers.zarantonello.dev:51000
              publicKey: dNUWq6FfG7+3AGl5olQOpVel6Ntl4brufEQOlN9VPEM=
            # srv-0-thi-home (no endpoint due to firewall restrictions)
            - allowedIPs:
                - 10.95.0.3/32
                - fda9:b00c:8b29:33f9::1095:3/128
              publicKey: j5Afx7hXJkjHHmDuzmScMrjL3oWpZxT6WL6xMIX87H0=
          privateKey: ENC[AES256_GCM,data:wlFtY2+VLsnCjrVJbH5s1KD2fOyEJ8dS28WtT0VBLhYlU10JSk0T1TVWUFc=,iv:X2zp+PZjEu3XdHDKIna46Dcyi2EdPjRCjA97pM4YaBg=,tag:FT0qEaNFL7WiavrJ2y4pXw==,type:str]
  nodeAnnotations:
    # yamllint disable-line rule:quoted-strings
    node.longhorn.io/default-disks-config: '[{ "path": "/var/mnt/longhorn-0", "allowScheduling":true }]'
  nodeLabels:
    node.longhorn.io/create-default-disk: config
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWHdQUGQwZVRpT2Z0ak51
        bk9IUFFCbUFVMGFKM1BwVHE4MlFVUlpkdldrClBCWXNvR29oWGFWRUxnTHZOZnVD
        ZVk1aDQvVU9OODZHOGtwaXZFZno0NWMKLS0tIHVkcXJqQy9TZHVXKzdkcEZzQUll
        T3ZzdU01bEpnWW83eHpwdXV5VVpJbFEKdhbaRfyi7sAlX/uFqckbRPRLndZ97dde
        vx6dEinsA6dpjbJU501+6oLOGZMk7ZxKynXefcOK+gMb7RoI2QUSPA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10s8xudjc20ujqjsk0asex5vgxqtm3fzrx2g3lzt5lls4rsay6cpqx6rhcc
  encrypted_regex: privateKey
  lastmodified: "2025-09-09T14:56:51Z"
  mac: ENC[AES256_GCM,data:s+Q1lHCW1qrhFgTV+bU4HCU4NEuW8vWya/nSK5qeQ3J5c+jz8GNsYaej7ftgH2UpAqAqdsh2Cw3C2V2a9KlfCBEernTGCdDRzZgM0aZBB+k1q690lfZh9+8CAB88JD0gaq6zW2bbYCf2GiIRc3c9WmcpJbuFGCTnD0qgliyGixc=,iv:kfunBy3fVTrhQm4XcygRPAJPMvFZ4btsKT28yXR1/0I=,tag:3dfOkQaTmoZeEqV0ZJIDVQ==,type:str]
  version: 3.10.2
