# See deployments/_patches/shared.yaml for base deployment definition.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo-runner-srv-hetz-nbg-0
spec:
  selector:
    matchLabels:
      apps.zarantonello.dev/variant: srv-hetz-nbg-0
  template:
    metadata:
      labels:
        apps.zarantonello.dev/variant: srv-hetz-nbg-0
    spec:
      containers:
        - env:
            - name: RUNNER_UUID
              valueFrom:
                secretKeyRef:
                  key: RUNNER_UUID
                  name: srv-hetz-nbg-0-env
          name: runner
      nodeSelector:
        kubernetes.io/hostname: srv-hetz-nbg-0
      volumes:
        - name: runner-token
          secret:
            secretName: srv-hetz-nbg-0-env
