concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  check-commitizen:
    container:
      image: git.zarantonello.dev/infra/ci:v2.3.22@sha256:8ece2e31a94773f1acdde8953e34efd346faa29e18e59e2f4dccbd1ba360eab3
    runs-on: srv-generic
    steps:
      - run: cz check --message '${{ forge.event.pull_request.title }}'

"on":
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
