concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.job }}

jobs:
  check-yamllint:
    container:
      image: git.zarantonello.dev/infra/ci:v1.1.17@sha256:f6a47aa3851cade029b55fe5e4303dfe8971d57061265b6f357b689109d8af8e
    runs-on: srv-generic
    steps:
      - uses: https://data.forgejo.org/actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - run: yamllint .

"on":
  pull_request:
    branches:
      - main
