concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.job }}

jobs:
  check-commitizen:
    container:
      image: git.zarantonello.dev/infra/ci:v1.1.26@sha256:a909d6507cd5dcd7567596a379c91ff73a514002a499941f433762ce463174cb
    runs-on: srv-generic
    steps:
      - run: cz check --message '${{ forge.event.pull_request.title }}'

"on":
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
