concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.job }}

jobs:
  check-yamllint:
    container:
      image: git.zarantonello.dev/infra/ci:v1.1.31@sha256:1bce306ea67ca15a1d887db7798900914e4240f0e71f0e2b036002d63b5fac09
    runs-on: srv-generic
    steps:
      - uses: https://data.forgejo.org/actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - run: yamllint .

"on":
  pull_request:
    branches:
      - main
