concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.job }}

jobs:
  check-prettier:
    container:
      image: git.zarantonello.dev/infra/ci:v2.2.5@sha256:e82d94156b2e56b4d67a92dbd701777cf174f9428a2fa00ba0d13a8d04cb9824
    runs-on: srv-generic
    steps:
      - uses: https://data.forgejo.org/actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - run: prettier --check .

"on":
  pull_request:
    branches:
      - main
