concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  check-prettier:
    container:
      image: git.zarantonello.dev/infra/ci-prettier:v1.0.1@sha256:1e96f8dfa172b2c012e196785a7f1a8bf9c9e17f37d489865b047e24e1c65177
    name: Check files formatting
    runs-on: srv-generic
    steps:
      - name: Clone the repository
        run: |
          git clone --filter=blob:none --no-checkout https://${{ forge.token }}@git.zarantonello.dev/${{ forge.repository }} ${{ forge.workspace }};
          git checkout --quiet ${{ forge.sha }};
      - name: Run prettier
        run: prettier --check .

name: check-prettier.yaml

"on":
  pull_request:
    branches:
      - main
