concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  check-prettier:
    container:
      image: git.zarantonello.dev/infra/ci-prettier:v1.0.2@sha256:71b6db7670f6b3b39de972a8e2611bb79f3d610f8679182361012c02e20ab584
    name: Check files formatting
    runs-on: srv-generic
    steps:
      - name: Clone the repository
        run: |
          git clone --filter=blob:none --no-checkout https://${{ forge.token }}@git.zarantonello.dev/${{ forge.repository }} ${{ forge.workspace }};
          git checkout --quiet ${{ forge.sha }};
      - name: Run prettier
        run: prettier --check .

name: check-prettier.yaml

"on":
  pull_request:
    branches:
      - main
