concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.job }}

jobs:
  check-commitizen:
    container:
      image: git.zarantonello.dev/infra/ci:v1.1.5@sha256:f28b7d8db92e764fbe642064bc98530abc26b748b4bd14999725e3af2e2f5bb3
    runs-on: srv-generic
    steps:
      - run: cz check --message '${{ forge.event.pull_request.title }}'

"on":
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
