concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  check-yamllint:
    container:
      image: git.zarantonello.dev/infra/ci-yamllint:latest@sha256:482408d4cdcbe4b371327eedf3caa537f9b718d10deac2c31bbc6b857ab4d85b
    name: Lint yaml files
    runs-on: srv-generic
    steps:
      - name: Clone the repository
        run: |
          git clone --filter=blob:none --no-checkout https://${{ forge.token }}@git.zarantonello.dev/${{ forge.repository }} ${{ forge.workspace }};
          git checkout --quiet ${{ forge.sha }};
      - name: Run yamllint
        run: yamllint .

name: check-yamllint.yaml

"on":
  pull_request:
    branches:
      - main
