apiVersion: v1alpha1
kind: ResolverConfig
# We can't use blocky since DNS is required to boot the node hosting blocky.
nameservers:
  - address: 1.1.1.1
    protocol: DoH
    tlsServerName: cloudflare-dns.com
  - address: 9.9.9.9
    protocol: DoT
    tlsServerName: dns.quad9.net
searchDomains:
  # Causes issues in alpine pods when enabled.
  disableDefault: true
---
apiVersion: v1alpha1
kind: KubeNodeConfig
nodeIP:
  validSubnets:
    - 100.64.0.0/10
    - fd7a:115c:a1e0::/48
---
apiVersion: v1alpha1
dnsDomain: k8s.zarantonello.dev
kind: KubeNetworkConfig
# Use same node subnet size for both IPv4 and IPv6 since pods need both of them
# anyway.
nodeCIDRMaskSizeIPv4: 24
nodeCIDRMaskSizeIPv6: 120
# The default CIDRs don't assign IPv6 addresses. So we override them with
# ones that do.
podSubnets:
  - 10.96.0.0/16
  - fda9:b00c:8b29:33f9::1096:0/112
serviceSubnets:
  - 10.97.0.0/16
  - fda9:b00c:8b29:33f9::1097:0/112
---
apiVersion: v1alpha1
clusterDNS:
  - 10.97.0.10
kind: KubeletConfig
---
apiVersion: v1alpha1
enabled: true
filters:
  endpoints:
    - 0.0.0.0/0
    - ::/0
    # Don't create wireguard tunnels encapsulated in tailscale tunnel.
    - "!100.64.0.0/10"
    - "!fd7a:115c:a1e0::/48"
kind: KubeSpanConfig
