apiVersion: v1alpha1
# All variables below will be encrypted by sops, these are the clear values for
# the non secret ones.
# - TS_ENABLE_METRICS=true
# Also remember to set TS_AUTHKEY.
environment:
  - ENC[AES256_GCM,data:S1sw91SZWN1WaOWcgix/alY/lvPzng==,iv:1UDoRtT7BYdEqtGzqQvHZfFEjoLI5O0qQrMKhQsb4Ng=,tag:vS835Ae4V5NVZ2XmYPnQOg==,type:str]
  - ENC[AES256_GCM,data:OBAxieMC0II2LffnMAxvaVbbu+Rs/NJUtlDbFn1y//zIwtAJ0OrRifL3U/teNrKsVH/Z186dx8fYBtsZRZrtfLhUnCNBBzZt,iv:t+ypZ7Ew+EP6wIVdNyNmnKkOS1wmKJCxKeWywr0T3Aw=,tag:1EpGdLRzlfjaiua0JgGYpA==,type:str]
kind: ExtensionServiceConfig
name: tailscale
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqMXVrZy9ZV2RWN2RHLzBP
        aitxZlFLc3NidXdYTG9KZDYxTkd0bngxNUVBCmhyUUh4c09FNUYyUDJlbGRmUUti
        ZVV1ZFh4OTJjZU85NUhFblB1T2FYMDgKLS0tIGRRUTBGZms5TjlRcHZhTmcxaDhE
        SXF4Y25MR3owZFRjbllTUWFJdXRsQVkKsJeeC0Tu9NkZ1KmlAPfVM4K6lKC8nez4
        uiwJpzDsLEJ+nHC6qO5cFXNMXOcjdmYECpkAWg7ic6/RP9YU+WF/6A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10s8xudjc20ujqjsk0asex5vgxqtm3fzrx2g3lzt5lls4rsay6cpqx6rhcc
  encrypted_regex: environment
  lastmodified: "2025-09-05T09:30:47Z"
  mac: ENC[AES256_GCM,data:znNhi+9+G5H/YhIyE+dcY8hM8+XNAIpGpb+YWQJaBgTd/kg7pUiCVocaP6zfDTMCWkmZksF/BYFIt289snc67ovV/PqUAfJVcFeT8ca+UcPgKoZo0XdbVyVmF6OUQWcp08aRRLkh1AWfXnE9dqMalP0Q07jR3LYI6TBqm/dAIM0=,iv:7V6a3lokR0SobEjz2NWtEjcko6+SHjtREbqSZeDNevk=,tag:F+vHQ0hhk3wh1k6n9IlJzw==,type:str]
  version: 3.10.2
