apiVersion: v1alpha1
environment:
  - ENC[AES256_GCM,data:+3vbmzo7OKskmkCWeL5lm8hQkyXqBBdJA/teG/KNo8L1LDmF0TOYGbJTjFFZJROVPpSXfv2QgX6kVBQMd4VpU8DiTf5wyoHbug==,iv:EREz1+llV2h2E50fsta2t7qRvl0i7tMYu4RDoLyvuOU=,tag:/sUhDVLaK2Wb2IfeGlGFGQ==,type:str]
  - ENC[AES256_GCM,data:v276+EJmupjxeKnZfrNYi8BDBE58rBgXj+GeUEZNl8EJj08=,iv:CiEKdIBIvNumI/IKrFZz1RIAB9mxGTX+SB2npc0QAm4=,tag:B31RZUPYk30qmAAR5bUzhA==,type:str]
kind: ExtensionServiceConfig
name: tailscale
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMlQ0dUl4aDJOS2RiWllT
        WlRNUEtmR01sbjZGRm9yQU5DVkxWbm9WbG40CkVCWlkzL2U3ZzVGbWRyKzc4OUFs
        YUw2MUlXMkxERjFUalhuc0RRaHBpL00KLS0tIENORkpwK1IyL0ZJNEdueWhjUER0
        Vlp3SUhLbnFERjZXREEydzNKNTY4MGMKbY63TmjIlQ7P2ugq78Smgd25lai70IoB
        O+echXUo55Q79qp//oxiu/un0GYJbVkcPWZuuKo/MnTBCSzEAv5bSg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1cyyv047n8zvzhadswewg7vdfzna0eslhvajwn782sypnpnks5u5svgjswh
  encrypted_regex: environment
  lastmodified: "2026-09-21T14:44:47Z"
  mac: ENC[AES256_GCM,data:3rtThkD12fRGoHQF0P8cPY5zVkUvDoZyUTAaZZFJtkFuWDH6Cb9pM7+3kC9AZvAzvBnQ4Hv5NepTGe09RMQVz0COylDJJmzHZvKPsLAFP5JXnGnUqRk552DPverMxmejdlcTGyVAC3rEiBl+8gsPuxjHt53J6C8GPhtiEHDWeRY=,iv:irZXrehAtoQw4DSl8mARDHDRO+QDgOcxHWa5HcX90og=,tag:3+N4K0H7u0+OjhwpjeJehg==,type:str]
  version: 3.13.2
