apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: machine-learning-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
