apiVersion: v1
kind: Service
metadata:
  name: http
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    apps.zarantonello.dev/name: forgejo
    apps.zarantonello.dev/namespace: forgejo
