apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: host-firewall
spec:
  ingress:
    - fromEntities:
        - cluster
    - fromCIDR:
        - 100.0.0.0/8
      toPorts:
        - ports:
            # Allow access to k8s api server from tailscale.
            - port: "6443"
              protocol: TCP
            # Allow access to talos api server from tailscale.
            - port: "50000"
              protocol: TCP
    - fromEntities:
        - world
      toPorts:
        - ports:
            # Allow wireguard ingress.
            - port: "56680"
              protocol: UDP
            # Allow tailscale ingress.
            - port: "41641"
              protocol: UDP
  nodeSelector:
    matchLabels:
      node.zarantonello.dev/firewall: "true"
