apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: infra-kubernetes
spec:
  interval: 10m
  ref:
    branch: main
  url: http://http.forgejo.svc.k8s.zarantonello.dev/infra/kubernetes.git
