apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  chart:
    spec:
      chart: longhorn
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn
      version: 1.9.1
  install:
    crds: Create
  interval: 5m
  releaseName: longhorn
  upgrade:
    crds: Create
  values:
    csi:
      attacherReplicaCount: 1
      provisionerReplicaCount: 1
      resizerReplicaCount: 1
      snapshotterReplicaCount: 1
    defaultSettings:
      # Enables automatic upgrades of Longhorn engine.
      concurrentAutomaticEngineUpgradePerNodeLimit: 1
      # Gets node disks from annotation.
      createDefaultDiskLabeledNodes: true
      # Removes update checker in the Longhorn UI.
      upgradeChecker: false
    longhornUI:
      replicas: 1
    persistence:
      defaultClassReplicaCount: 1
      defaultDataLocality: strict-local
      migratable: false
      reclaimPolicy: Retain
      volumeBindingMode: Immediate
