apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: srv-hetz-nbg-0-tailscale-submissions
spec:
  addresses:
    - type: IPAddress
      value: 100.83.193.88
  gatewayClassName: cilium
  infrastructure:
    annotations:
      lbipam.cilium.io/sharing-cross-namespace: "*"
      lbipam.cilium.io/sharing-key: srv-hetz-nbg-0-tailscale
  listeners:
    - allowedRoutes:
        namespaces:
          from: All
      name: submissions
      port: 465
      protocol: TCP
