apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: srv-hetz-nbg-0-tailscale-dns
spec:
  addresses:
    - type: IPAddress
      value: 100.83.193.88
  gatewayClassName: cilium
  infrastructure:
    annotations:
      lbipam.cilium.io/sharing-cross-namespace: "*"
      lbipam.cilium.io/sharing-key: srv-hetz-nbg-0-tailscale
  listeners:
    - allowedRoutes: &allowedRoutes
        namespaces:
          from: All
      name: dns-tcp
      port: 53
      protocol: TCP
    - allowedRoutes: *allowedRoutes
      name: dns-udp
      port: 53
      protocol: UDP
