apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: srv-hetz-nbg-0-tailscale-imaps
spec:
  addresses:
    - type: IPAddress
      value: 100.105.222.83
    - type: IPAddress
      value: fd7a:115c:a1e0::cd36:de54
  gatewayClassName: cilium
  infrastructure:
    annotations:
      lbipam.cilium.io/sharing-cross-namespace: "*"
      lbipam.cilium.io/sharing-key: srv-hetz-nbg-0-tailscale
  listeners:
    - allowedRoutes:
        namespaces:
          from: All
      name: submissions
      port: 993
      protocol: TCP
