apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: srv-hetz-nbg-0-internal-http
spec:
  gatewayClassName: cilium
  listeners:
    - allowedRoutes: &allowedRoutes
        namespaces:
          from: All
      hostname: "*.zarantonello.net"
      name: http-zarantonello-net
      port: 80
      protocol: HTTP
    - allowedRoutes: *allowedRoutes
      hostname: "*.zarantonello.dev"
      name: http-zarantonello-dev
      port: 80
      protocol: HTTP
