apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-controller
spec:
  selector:
    matchLabels:
      apps.zarantonello.dev/name: source-controller
      apps.zarantonello.dev/namespace: fluxcd
  template:
    metadata:
      annotations:
        monitoring.zarantonello.dev/metrics-0-id: 2ecdc56b-e350-4c78-8cf7-8b32801343a4
        monitoring.zarantonello.dev/metrics-0-port: "8080"
      labels:
        apps.zarantonello.dev/name: source-controller
        apps.zarantonello.dev/namespace: fluxcd
    spec:
      containers:
        - args:
            - --enable-leader-election
            - --storage-path=/data
            - --storage-adv-addr=source-controller.fluxcd.svc.k8s.zarantonello.dev
          image: ghcr.io/fluxcd/source-controller:v1.7.2@sha256:030e258b636fede22a41bcaea3ea4542035cc280b0c740f641c4c5efb904b980
          name: source-controller
          ports:
            - containerPort: 9090
              name: http
            - containerPort: 8080
              name: http-metrics
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /data
              name: data
      enableServiceLinks: false
      securityContext:
        fsGroup: 20791
        runAsGroup: 20791
        runAsNonRoot: true
        runAsUser: 20791
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: source-controller
      volumes:
        - emptyDir: {}
          name: tmp
        - emptyDir: {}
          name: data
