apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: transmission
resources:
  - deployments/caddy.yaml
  - deployments/transmission.yaml
  - dnsrecord.yaml
  - http-routes/caddy.yaml
  - http-routes/transmission.yaml
  - kustomization.flux.yaml
  - namespace.yaml
  - persistent-volume-claims/config.yaml
  - persistent-volume-claims/data.yaml
  - persistent-volumes/transmission-config.yaml
  - persistent-volumes/transmission-data.yaml
  - service-accounts/default.yaml
  - services/bittorrent.yaml
  - services/caddy-http.yaml
  - services/transmission-http.yaml
  - tcp-routes/bittorrent.yaml
  - udp-routes/bittorrent.yaml
