apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
  - files:
      - _generated/configs/config.yaml
    name: runner-config
kind: Kustomization
namespace: forgejo-runner
patches:
  - path: deployments/_patches/forgejo-runner-shared.yaml
    target:
      kind: Deployment
      name: forgejo-runner-.+
resources:
  - deployments/forgejo-runner-srv-hetz-nbg-0.yaml
  - deployments/forgejo-runner-srv-home.yaml
  - kustomization.flux.yaml
  - namespace.yaml
  - service-accounts/default.yml
secretGenerator:
  - envs:
      - _generated/secrets/srv-home.env
    name: srv-home-env
  - envs:
      - _generated/secrets/srv-hetz-nbg-0.env
    name: srv-hetz-nbg-0-env
