apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
  - envs:
      - _generated/configs/immich.env
    name: server-env
kind: Kustomization
namespace: immich
resources:
  - deployments/machine-learning.yaml
  - deployments/postgres.yaml
  - deployments/redis.yaml
  - deployments/server.yaml
  - dnsrecord.yaml
  - http-routes/default.yaml
  - kustomization.flux.yaml
  - namespace.yaml
  - persistent-volume-claims/machine-learning-cache.yaml
  - persistent-volume-claims/postgres-data.yaml
  - persistent-volume-claims/redis-data.yaml
  - persistent-volume-claims/server-data.yaml
  - persistent-volumes/immich-machine-learning-cache.yaml
  - persistent-volumes/immich-postgres-data.yaml
  - persistent-volumes/immich-redis-data.yaml
  - persistent-volumes/immich-server-data.yaml
  - service-accounts/default.yaml
  - services/machine-learning-http.yaml
  - services/postgres.yaml
  - services/redis.yaml
  - services/server-http.yaml
secretGenerator:
  - envs:
      - _generated/secrets/postgres.env
    name: postgres-env
