apiVersion: v1
kind: Secret
metadata:
  name: acme-cloudflare-dns-api-token
stringData:
  TOKEN: ENC[AES256_GCM,data:LszIHsquszOdsYuaimQMArYvydvHjrxNR6NZ8sCrJSmh+g+fxzrDIFhe2J+cuOoXXYF/huQ=,iv:GVmUf4aSTtnfkwIsm8bfq+ABQDVlLMV33VzepB+rW78=,tag:JcMi+x7lc8tmxhHVfVOygg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQOGFqWksvQUtDYUxLYW9O
        UXdMTCtvdWY2Q3llaTFHTDhzRjV0WC9aZW5FCmxYdVNUOGlXbVc2ZHd3SkVnV2Iv
        TDhHZFY3b01QQ2NSK1ZMMTRQMUdPRTAKLS0tIEJicklSdndhOTh0cXF4cEZESFBT
        TjIrU3JQajJ0SEEwZjRnc2QwbDg4MEUKS0q81/JI9okOYUdjnUy+Z11znf9SqTUJ
        cKrEPYTTEOXmXasQWIJ1G8H4Te/L0Ls9aM8OsCniv+OlPkYOPDHTpQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1cyyv047n8zvzhadswewg7vdfzna0eslhvajwn782sypnpnks5u5svgjswh
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-25T10:08:17Z"
  mac: ENC[AES256_GCM,data:xPKKM15d0gqTY2H1XMcEyFvkXO0Sx7b2D67Xp8rF/MIz9fKXnahvs/TGSNz86SGFHH+oPIwe1cosAWN7E4KmV4CquENBy0rm5K0+B4YV0nOJQ/dRbpr9VsEkPegXs966V3efrfqWsgoGRM/+F2ipnYYPZHQbg62B4uneh2uMC5c=,iv:Op+2ORN2UavS4CVXRdZYpN+T74H7FztcdsA1UkR3Km0=,tag:nRUEiew6zwEdPajzmL5QWA==,type:str]
  version: 3.13.2
