apiVersion: gateway.networking.k8s.io/v1
kind: UDPRoute
metadata:
  name: dns
spec:
  parentRefs:
    - name: srv-home-lan-dns
      namespace: cilium
    - name: srv-home-tailscale-dns
      namespace: cilium
  rules:
    - backendRefs:
        - name: dns
          port: 53
