apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cilium
resources:
  # Get gateway api crds from the github repo.
  - https://github.com/kubernetes-sigs/gateway-api/config/crd/?ref=v1.6.2
  - certificates/zarantonello-dev.yaml
  - certificates/zarantonello-net.yaml
  # - cilium-clusterwide-network-policies/dns-visibility-blocky.yaml
  # - cilium-clusterwide-network-policies/dns-visibility-coredns.yaml
  # - cilium-clusterwide-network-policies/host-firewall.yaml
  - cilium-gateway-class-configs/access-logs.yaml
  - cilium-loadbalancer-ip-pools/srv-hetz-nbg-0-public.yaml
  - cilium-loadbalancer-ip-pools/srv-hetz-nbg-0-tailscale.yaml
  - cilium-loadbalancer-ip-pools/srv-home-lan.yaml
  - cilium-loadbalancer-ip-pools/srv-home-tailscale.yaml
  - gateway-classes/cilium-access-logs.yaml
  - gateways/srv-hetz-nbg-0-public-https.yaml
  - gateways/srv-hetz-nbg-0-public-smtp.yaml
  - gateways/srv-hetz-nbg-0-tailscale-dns.yaml
  - gateways/srv-hetz-nbg-0-tailscale-http.yaml
  - gateways/srv-hetz-nbg-0-tailscale-https.yaml
  - gateways/srv-hetz-nbg-0-tailscale-imaps.yaml
  - gateways/srv-hetz-nbg-0-tailscale-submissions.yaml
  - gateways/srv-home-lan-bittorrent.yaml
  - gateways/srv-home-lan-dns.yaml
  - gateways/srv-home-tailscale-dns.yaml
  - gateways/srv-home-tailscale-http.yaml
  - gateways/srv-home-tailscale-https.yaml
  - helm-releases/cilium.yaml
  - helm-repositories/cilium.yaml
  - kustomization.flux.yaml
  - namespace.yaml
  - service-accounts/default.yaml
