apiVersion: v1alpha1
auto: "off"
hostname: srv-hetz-nbg-0.servers.zarantonello.dev
kind: HostnameConfig
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  diskSelector:
    match: disk.dev_path == "/dev/sda"
  maxSize: 30GiB
  minSize: 30GiB
---
apiVersion: v1alpha1
kind: ZswapConfig
maxPoolPercent: 25
---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: data-0
provisioning:
  diskSelector:
    match: disk.dev_path == "/dev/sda"
  grow: true
  minSize: 1GiB
---
apiVersion: v1alpha1
kind: DHCPv4Config
name: enp1s0
---
addresses:
  - address: 2a01:4f8:1c1a:3498::/64
apiVersion: v1alpha1
kind: LinkConfig
name: enp1s0
routes:
  - gateway: fe80::1
