apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  diskSelector:
    match: disk.dev_path == "/dev/sda"
  maxSize: 30GiB
  minSize: 30GiB
---
apiVersion: v1alpha1
kind: ZswapConfig
maxPoolPercent: 25
---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: data-0
provisioning:
  diskSelector:
    match: disk.dev_path == "/dev/sda"
  grow: true
  minSize: 1GiB
