addresses:
  - address: 10.95.0.3/24
  - address: fda9:b00c:8b29:33f9::1095:3/120
apiVersion: v1alpha1
kind: WireguardConfig
listenPort: 51000
name: wg0
peers:
  # srv-0-cor-home
  - allowedIPs:
      - 10.95.0.2/32
      - fda9:b00c:8b29:33f9::1095:2/128
    endpoint: 95.232.179.210:51000
    publicKey: dNUWq6FfG7+3AGl5olQOpVel6Ntl4brufEQOlN9VPEM=
  # srv-0-nbg-hetz
  - allowedIPs:
      - 10.95.0.1/32
      - fda9:b00c:8b29:33f9::1095:1/128
    endpoint: 78.47.155.111:51000
    publicKey: BgTeLVv2UKMD86N0XyQoTjh9sKSo/SkMfYKr1VQ3VRc=
privateKey: ENC[AES256_GCM,data:L8W0WpChSrI6viJIay8cA6Xvo3jZZTVJ0pGz1OBUWkMz8NxVcTPSfNYNH1U=,iv:yKG51ePZ7Y713WUYmpWsrJQjIJYVLpELF2Gp7IwjRCI=,tag:8bP7OJATw4K5fyA9ugM/FQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RlpsZE8zb3JVNkxydkow
        TDB3UXhkVUdNUnNGUlcySVR2Mkw0MWMyN1RNCmNYQjNFeTFETHBPQWRaR2FNNGd2
        RnFwVWluNG1razJjbTFpYUtoSDJHUnMKLS0tIHZqM2Zwc1I2dzRReTFaa0gxWllx
        L2pNdWVSSGpHN0RtZTdaMW5xQkc5MjgKzaHjS/wCcpaI6DdZBE/1pH3t285/pD+W
        Sh1QOczpGfyFMSNhV4IpkgIxvKfDxC8Vhsh4kM0qhMiMkS7HCxWGwQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10s8xudjc20ujqjsk0asex5vgxqtm3fzrx2g3lzt5lls4rsay6cpqx6rhcc
  encrypted_regex: privateKey
  lastmodified: "2026-01-03T12:12:30Z"
  mac: ENC[AES256_GCM,data:mFBWyJEFFxgGXcnkNVMONDh95F0rzmxGDGIKTsC9MA2ble9JQ2ffDbhEivAi5lN8KEh6GfZvOCNAZ8RHbX7UqQrg1BkEvT00ZTAcZ5HT1Fko7cweQqDriZvauy8ndLdffqGXiQuCVQHA2Qmm0hx8tIj0iwFCbYBztftlZQYqsk8=,iv:r4kQhwZLzflS6D4AGK9doCVMe3a6udRrn26UAy2bEyY=,tag:Pk5hC+JAYNysCqTqDOqRsA==,type:str]
  version: 3.11.0
