apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  local:
    path: /var/mnt/data-0/transmission-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - srv-0-cor-home
