apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
  - envs:
      - _generated/configs/server.env
    name: server-env
kind: Kustomization
namespace: umami
resources:
  - deployments/server.yaml
  - deployments/postgres.yaml
  - http-routes/public.yaml
  - http-routes/tailscale.yaml
  - kustomization.flux.yaml
  - namespace.yaml
  - persistent-volume-claims/postgres-data.yaml
  - persistent-volumes/umami-postgres-data.yaml
  - service-accounts/default.yaml
  - services/postgres.yaml
  - services/server.yaml
secretGenerator:
  - envs:
      - _generated/secrets/postgres.env
    name: postgres-env
