apiVersion: v1alpha1
# All variables below will be encrypted by sops, these are the clear values for
# the non secret ones.
# - TS_ENABLE_METRICS=true
# Also remember to set TS_AUTHKEY.
environment:
  - ENC[AES256_GCM,data:D0LB5DKni8Idk2ZGNjeU4T2xkqc1jg==,iv:izBrkzpKgji8P9pFm1+gohEYUJvH67EEwsnfhDNgdfs=,tag:l59/Z5E5LPVGa1xaWARK1A==,type:str]
  - ENC[AES256_GCM,data:vX3pv4TxeYsy8TMgiCzXekv1f+3R8YoDh3qoxffJqNzY88jfkCn+4mYlBzPMXRyla+2KLA9KZIFA19iknlZ31ATdBzegPZfe8A==,iv:bAHVKY1xistNZSM9+pEHd3zjmxLDn/caxH2Ku2IbrVY=,tag:FIsIUmQsjyUmUvnYR3tbHg==,type:str]
kind: ExtensionServiceConfig
name: tailscale
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBka25JTW1aZG5lWVU4RTlI
        MUhESWhWbng4MndVd1pjZTRRL21nYlRSY1RZCmlPVktRQ05MTEVxb3RvN2daUm1W
        NUlXYVl0MHdmVldTbXZ5UU9tQll0b3MKLS0tIHNjTlR2KzB4anZsd1dJdzhvNFJI
        aVlvRGQxdzFCUDVkTlJhc3N4RTArcncKB3kuc6MnBkIR1fklOvdBKL3M5o2WGnxu
        iq04JiKFI8u9M9kzLUMayhyUx04ksjjE3Mt7PbUYEUIiLG97DJ3SBA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1cyyv047n8zvzhadswewg7vdfzna0eslhvajwn782sypnpnks5u5svgjswh
  encrypted_regex: environment
  lastmodified: "2026-07-25T10:14:24Z"
  mac: ENC[AES256_GCM,data:Yl7hAXSVO2BD507ZZGljtZNphoRrkVGMrIvwir9Z4AvL+eXu/Y+z8enMC2Hr0sAfGcJp28UCyxX7WeLn4lbbvgUbtUexIK+/X86Q3tri9QuGl9DIb6n+WQQHVM0mKXKlIPi4tSUV6yAwBXZ9XXOzYoYTc3VPrlDqQB0B2TtVDq8=,iv:+/xCUy+Q90EBSLCl74I6llGpIhqaScp4nk5x6I/0Gt4=,tag:jV0+ZxzjGDL3ShxEGTq18Q==,type:str]
  version: 3.13.2
