apiVersion: v1alpha1
environment:
  - ENC[AES256_GCM,data:b5vWFk5qLnwYdoXMvh93MiQhzGOxghzgh+/po60OgaHYH0anCMYeChBBQxTRHQMcMDdvnlA63d6BY2/RJ5F44HnrLVvoqqf+XQ==,iv:f15vOgpyKa7+nerZBoVIVgni3WUemUuz0j0eoQuWnXo=,tag:LpaDDz0WFFcfT1D3TiE23A==,type:str]
kind: ExtensionServiceConfig
name: tailscale
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMEtkYmZJdlBIU25rTTND
        Tlc2dmxzWUhBUHl4a0ZhWS81dWFrU2VudTNZCk1JR3dreEI2NmxIakxJK0NLMUJV
        UUNTOGVGNG8zaXM3UmlvbXQrc1lpbjgKLS0tIGR4MFBiS2QvUnpBNHhWOEQwOWJm
        akR3QW5YbWRDNUhwK2VrTGRtVjU2bjAKt8bHycKG6HDjMiEL579oPhYMzWGrEsWN
        ZiiAdYLKwyS2o8pjq0/c7c1+zfd0eHCh0e7TA6dxsjHVi0QqCittGg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1cyyv047n8zvzhadswewg7vdfzna0eslhvajwn782sypnpnks5u5svgjswh
  encrypted_regex: environment
  lastmodified: "2026-08-16T15:53:13Z"
  mac: ENC[AES256_GCM,data:6AgzLj4t/q0s62pP6CDga+x9f98zx1JQEmbt2HqDZr/Ehc0W3c2o6NcSfKIYKeMvdcfENRhRyeLWzVxjToVFcSiQpQiwk8NEybKGNJ1wSK/c8VhDFK0sJfW44FEepb5FBz2bqLs9D/oxoCMXKRcw5+42ExVrTofHI2y8mDA9uT4=,iv:yXHwrxe8hcjgIbsgXrcXaeL01MyBsnhhkRZ5zqpog58=,tag:/3w6HRcdwodJIdImGCqCZg==,type:str]
  version: 3.13.2
