apiVersion: apps/v1
kind: Deployment
metadata:
  # Kustomize requires a name here, but it isn't used.
  name: forgejo-runner
spec:
  selector:
    matchLabels:
      apps.zarantonello.dev/name: forgejo-runner
      apps.zarantonello.dev/namespace: forgejo-runner
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        apps.zarantonello.dev/name: forgejo-runner
        apps.zarantonello.dev/namespace: forgejo-runner
    spec:
      containers:
        - command:
            - forgejo-runner
            - daemon
            - --url=http://http.forgejo.svc.k8s.zarantonello.dev
            - --uuid=$(RUNNER_UUID)
            - --token-url=file:///data/token
            - --label=$(NODE_NAME):docker://busybox
            - --label=srv-generic:docker://busybox
            - --config=/etc/runner/config.yaml
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          image: data.forgejo.org/forgejo/runner:12.13.2@sha256:eb6e7bc21973382d261e6eb883dbd27b8cb56939d33a3bfd79a1352b7f9a33a0
          name: runner
          resources:
            limits:
              # Restart container if caches are too big.
              ephemeral-storage: 10Gi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            # Docker daemon has to run as root.
            runAsGroup: 4880
            runAsNonRoot: true
            runAsUser: 4880
          volumeMounts:
            - mountPath: /etc/runner
              name: runner-config
            - mountPath: /data
              name: runner-data
            - mountPath: /data/token
              name: runner-token
              subPath: RUNNER_TOKEN
            - mountPath: /tmp
              name: runner-tmp
            - mountPath: /var/run
              name: docker-var-run
        - command:
            - dockerd
            - --no-new-privileges
            - --group=4880
          image: docker.io/library/docker:29.7.1-dind@sha256:e8faad5a8dc5279dff929afc5449f2791736912fff9f99351d742db2fad01b4c
          name: docker
          restartPolicy: Always
          securityContext:
            capabilities:
              drop:
                - ALL
            privileged: true
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /var/lib/docker
              name: docker-data
            - mountPath: /tmp
              name: docker-tmp
            - mountPath: /var/run
              name: docker-var-run
      enableServiceLinks: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      # Set to same value + 1 minute as the one in the runner config.
      terminationGracePeriodSeconds: 7200
      volumes:
        - configMap:
            name: runner-config
          name: runner-config
        - emptyDir: {}
          name: runner-tmp
        - emptyDir: {}
          name: runner-data
        - hostPath:
            path: /var/mnt/data-0/forgejo-runner-docker-data
          name: docker-data
        - emptyDir: {}
          name: docker-tmp
        - emptyDir: {}
          name: docker-var-run
