apiVersion: apps/v1
kind: Deployment
metadata:
  # Kustomize requires a name here, but it isn't used.
  name: forgejo-runner
spec:
  selector:
    matchLabels:
      apps.zarantonello.dev/name: forgejo-runner
      apps.zarantonello.dev/namespace: forgejo-runner
  # Ephemeral storage request is quite large, so sometimes scheduling fails.
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        apps.zarantonello.dev/name: forgejo-runner
        apps.zarantonello.dev/namespace: forgejo-runner
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            # Avoid having 2 runner pods on the same node.
            - labelSelector:
                matchLabels:
                  apps.zarantonello.dev/namespace: forgejo-runner
              topologyKey: kubernetes.io/hostname
      containers:
        - command:
            - forgejo-runner
            - daemon
            - --config=/etc/runner/config.yaml
          image: data.forgejo.org/forgejo/runner:11.2.0@sha256:85709f74716b64bf46f753676cec5299dd15010a4517fe4efdb2f84d31f4bbdd
          name: runner
          resources:
            limits:
              # Restart container if caches are too big.
              ephemeral-storage: 2Gi
          securityContext: &runnerSecurityContext
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            # Docker daemon has to run as root.
            runAsGroup: 4880
            runAsNonRoot: true
            runAsUser: 4880
          volumeMounts: &runnerVolumeMounts
            - mountPath: /etc/runner
              name: runner-config
            - mountPath: /data
              name: runner-data
            - mountPath: /tmp
              name: runner-tmp
            - mountPath: /var/run
              name: docker-var-run
      enableServiceLinks: false
      hostAliases:
        # Override this so that runners push directly to forgejo, without passing
        # through Cloudflare's proxy.
        - hostnames:
            - git.zarantonello.dev
          ip: 10.95.0.3
      initContainers:
        - command:
            - forgejo-runner
            - register
            - --no-interactive
            - --config=/etc/runner/config.yaml
            - --labels=$(NODE_NAME):docker://busybox,srv-$(NODE_TYPE):docker://busybox,srv-generic:docker://busybox
            - --instance=http://http.forgejo.svc.k8s.zarantonello.dev
            - --token=$(REGISTRATION_TOKEN)
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            # Allows to distinguish between 'large' and 'small' runners.
            - name: NODE_TYPE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['node.zarantonello.dev/type']
          envFrom:
            - secretRef:
                name: forgejo-runner-env
          image: data.forgejo.org/forgejo/runner:11.2.0@sha256:85709f74716b64bf46f753676cec5299dd15010a4517fe4efdb2f84d31f4bbdd
          name: register
          securityContext: *runnerSecurityContext
          volumeMounts: *runnerVolumeMounts
        - command:
            - dockerd
            - --no-new-privileges
            - --group=4880
          image: docker.io/library/docker:28.5.2-dind@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
          name: docker
          resources:
            limits:
              # Restart container if caches are too big.
              ephemeral-storage: 5Gi
          restartPolicy: Always
          securityContext:
            capabilities:
              drop:
                - ALL
            privileged: true
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /etc/docker
              name: docker-config
            - mountPath: /var/lib/docker
              name: docker-data
            - mountPath: /tmp
              name: docker-tmp
            - mountPath: /var/run
              name: docker-var-run
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      # Set to same value + 1 minute as the one in the runner config.
      terminationGracePeriodSeconds: 1800
      volumes:
        - configMap:
            name: runner-config
          name: runner-config
        - emptyDir: {}
          name: runner-tmp
        - emptyDir: {}
          name: runner-data
        - configMap:
            name: docker-config
          name: docker-config
        - emptyDir: {}
          name: docker-data
        - emptyDir: {}
          name: docker-tmp
        - emptyDir: {}
          name: docker-var-run
