apiVersion: apps/v1
kind: Deployment
metadata:
  # Kustomize requires a name here, but it isn't used.
  name: forgejo-runner
spec:
  selector:
    matchLabels:
      apps.zarantonello.dev/name: forgejo-runner
      apps.zarantonello.dev/namespace: forgejo-runner
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        apps.zarantonello.dev/name: forgejo-runner
        apps.zarantonello.dev/namespace: forgejo-runner
    spec:
      containers:
        - command:
            - forgejo-runner
            - daemon
            - --config=/etc/runner/config.yaml
          image: data.forgejo.org/forgejo/runner:12.5.2@sha256:6617b2c22b3369b18bc2017f97c28026e87e8a5217058e9c08d1ae4091b3a357
          name: runner
          resources:
            limits:
              # Restart container if caches are too big.
              ephemeral-storage: 5Gi
          securityContext: &runnerSecurityContext
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            # Docker daemon has to run as root.
            runAsGroup: 4880
            runAsNonRoot: true
            runAsUser: 4880
          volumeMounts: &runnerVolumeMounts
            - mountPath: /etc/runner
              name: runner-config
            - mountPath: /data
              name: runner-data
            - mountPath: /tmp
              name: runner-tmp
            - mountPath: /var/run
              name: docker-var-run
      enableServiceLinks: false
      hostAliases:
        # Override this so that runners connect directly to forgejo, without passing
        # through Cloudflare's proxy.
        - hostnames:
            - git.zarantonello.dev
          ip: 10.95.0.3
      initContainers:
        - command:
            - forgejo-runner
            - register
            - --no-interactive
            - --config=/etc/runner/config.yaml
            - --labels=$(NODE_NAME):docker://busybox,srv-$(NODE_TYPE):docker://busybox,srv-generic:docker://busybox
            - --instance=http://http.forgejo.svc.k8s.zarantonello.dev
            - --token=$(REGISTRATION_TOKEN)
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            # Allows to distinguish between 'large' and 'small' runners.
            - name: NODE_TYPE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['node.zarantonello.dev/type']
          envFrom:
            - secretRef:
                name: forgejo-runner-env
          image: data.forgejo.org/forgejo/runner:12.5.2@sha256:6617b2c22b3369b18bc2017f97c28026e87e8a5217058e9c08d1ae4091b3a357
          name: register
          securityContext: *runnerSecurityContext
          volumeMounts: *runnerVolumeMounts
        - command:
            - dockerd
            - --no-new-privileges
            - --group=4880
          image: docker.io/library/docker:29.1.4-dind@sha256:d95427251fd155cd69a03311a8c4edf6d0778595444afc2d2c800a156eb2ecac
          name: docker
          restartPolicy: Always
          securityContext:
            capabilities:
              drop:
                - ALL
            privileged: true
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /etc/docker
              name: docker-config
            - mountPath: /var/lib/docker
              name: docker-data
            - mountPath: /tmp
              name: docker-tmp
            - mountPath: /var/run
              name: docker-var-run
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      # Set to same value + 1 minute as the one in the runner config.
      terminationGracePeriodSeconds: 1800
      volumes:
        - configMap:
            name: runner-config
          name: runner-config
        - emptyDir: {}
          name: runner-tmp
        - emptyDir: {}
          name: runner-data
        - configMap:
            name: docker-config
          name: docker-config
        - hostPath:
            path: /var/mnt/data-0/forgejo-runner-docker-data
          name: docker-data
        - emptyDir: {}
          name: docker-tmp
        - emptyDir: {}
          name: docker-var-run
