apiVersion: apps/v1
kind: Deployment
metadata:
  # Kustomize requires a name here, but it isn't used.
  name: forgejo-runner
spec:
  selector:
    matchLabels:
      apps.zarantonello.dev/name: forgejo-runner
      apps.zarantonello.dev/namespace: forgejo-runner
  # Ephemeral storage request is quite large, so sometimes scheduling fails.
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        apps.zarantonello.dev/name: forgejo-runner
        apps.zarantonello.dev/namespace: forgejo-runner
    spec:
      containers:
        - command:
            - forgejo-runner
            - daemon
            - --config=/etc/runner/config.yaml
          env:
            - name: DOCKER_HOST
              value: tcp://127.0.0.1:2376
            - name: DOCKER_CERT_PATH
              value: /certs/client
            - name: DOCKER_TLS_VERIFY
              value: "1"
          image: data.forgejo.org/forgejo/runner:11.1.1@sha256:e435bb347f07ae0d1ed580afd993105e2470af83b3e9af3495ac6dcce7972f28
          name: runner
          resources:
            limits:
              # Restart container if caches are too big.
              ephemeral-storage: 2Gi
          securityContext: &runnerSecurityContext
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            # Docker daemon has to run as root.
            runAsGroup: 4880
            runAsNonRoot: true
            runAsUser: 4880
          volumeMounts: &runnerVolumeMounts
            - mountPath: /etc/runner
              name: runner-config
            - mountPath: /data
              name: runner-data
            - mountPath: /tmp
              name: runner-tmp
            - mountPath: /certs
              name: docker-certs
        - image: docker.io/library/docker:28.4.0-dind@sha256:2ceb471176ad51e37145d43ce7cbf0fa5d644a2b185bd537f0ef695fb3a37497
          name: docker
          resources:
            limits:
              # Restart container if caches are too big.
              ephemeral-storage: 3Gi
          securityContext:
            capabilities:
              drop:
                - ALL
            privileged: true
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /etc/docker
              name: docker-config
            - mountPath: /var/lib/docker
              name: docker-data
            - mountPath: /certs
              name: docker-certs
            - mountPath: /var/run
              name: docker-var-run
      enableServiceLinks: false
      hostAliases:
        # Override this so that runners push directly to forgejo, without passing
        # through Cloudflare's proxy.
        - hostnames:
            - git.zarantonello.dev
          ip: 10.95.0.3
      initContainers:
        - command:
            - forgejo-runner
            - register
            - --no-interactive
            - --config=/etc/runner/config.yaml
            - --labels=$(NODE_NAME):docker://busybox,srv-$(NODE_TYPE):docker://busybox,srv-generic:docker://busybox
            - --instance=http://http.forgejo.svc.k8s.zarantonello.dev
            - --token=$(REGISTRATION_TOKEN)
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            # Allows to distinguish between 'large' and 'small' runners.
            - name: NODE_TYPE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['node.zarantonello.dev/type']
          envFrom:
            - secretRef:
                name: forgejo-runner-env
          image: data.forgejo.org/forgejo/runner:11.1.1@sha256:e435bb347f07ae0d1ed580afd993105e2470af83b3e9af3495ac6dcce7972f28
          name: register
          securityContext: *runnerSecurityContext
          volumeMounts: *runnerVolumeMounts
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - configMap:
            name: runner-config
          name: runner-config
        - emptyDir: {}
          name: runner-tmp
        - emptyDir: {}
          name: runner-data
        - configMap:
            name: docker-config
          name: docker-config
        - emptyDir: {}
          name: docker-data
        - emptyDir: {}
          name: docker-certs
        - emptyDir: {}
          name: docker-var-run
