apiVersion: v1
kind: Service
metadata:
  annotations:
    lbipam.cilium.io/ips: 100.73.66.84
    lbipam.cilium.io/sharing-cross-namespace: "*"
    lbipam.cilium.io/sharing-key: srv-0-cor-home-tailscale
  name: minecraft
spec:
  ports:
    - name: minecraft
      port: 25565
      protocol: TCP
      targetPort: minecraft
  selector:
    apps.zarantonello.dev/name: minecraft
    apps.zarantonello.dev/namespace: minecraft
  type: LoadBalancer
