apiVersion: v1
kind: Service
metadata:
  name: minecraft
spec:
  ipFamilyPolicy: RequireDualStack
  ports:
    - name: minecraft
      port: 25565
      targetPort: minecraft
  selector:
    apps.zarantonello.dev/name: minecraft
    apps.zarantonello.dev/namespace: minecraft
