apiVersion: v1
kind: Service
metadata:
  name: kube-dns-rs
spec:
  clusterIP: 10.97.0.10
  ipFamilyPolicy: RequireDualStack
  ports:
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: dns-tcp
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: dns-udp
  selector:
    apps.zarantonello.dev/name: kube-dns-rs
    apps.zarantonello.dev/namespace: kube-dns-rs
  trafficDistribution: PreferSameNode
