apiVersion: v1
kind: PersistentVolume
metadata:
  name: vaultwarden-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  local:
    path: /var/mnt/data-0/vaultwarden-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - srv-0-nbg-hetz
