apiVersion: gateway.networking.k8s.io/v1
kind: UDPRoute
metadata:
  name: bittorrent
spec:
  parentRefs:
    - name: srv-home-lan-bittorrent
      namespace: cilium
  rules:
    - backendRefs:
        - name: bittorrent
          port: 51413
