apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: redis
  selector:
    apps.zarantonello.dev/name: redis
    apps.zarantonello.dev/namespace: immich
