apiVersion: v1
kind: Service
metadata:
  name: http
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    apps.zarantonello.dev/name: victorialogs
    apps.zarantonello.dev/namespace: victorialogs
