apiVersion: v1
kind: Service
metadata:
  name: source-controller
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    apps.zarantonello.dev/name: source-controller
    apps.zarantonello.dev/namespace: fluxcd
