apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      apps.zarantonello.dev/name: postgres
      apps.zarantonello.dev/namespace: immich
  # Persistent volume cannot be read by 2 replicas.
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        apps.zarantonello.dev/name: postgres
        apps.zarantonello.dev/namespace: immich
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: postgres-env
          image: ghcr.io/tensorchord/vchord-postgres:pg18-v1.1.1@sha256:700ff05ebdc7e4afd4dd8442e0684293046c3833677fec326550000a04cf8a91
          name: postgres
          ports:
            - containerPort: 5432
              name: postgres
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: data
            - mountPath: /tmp
              name: tmp
            - mountPath: /var/run/postgresql
              name: sockets
      enableServiceLinks: false
      nodeSelector:
        kubernetes.io/hostname: srv-home
      securityContext:
        runAsGroup: 999
        runAsNonRoot: true
        # User has to be 999, otherwise the container tries to chown the postgres
        # volume but fails due to insufficient permissions.
        runAsUser: 999
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - emptyDir: {}
          name: tmp
        - emptyDir: {}
          name: sockets
        - name: data
          persistentVolumeClaim:
            claimName: postgres-data
