apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      apps.zarantonello.dev/name: redis
      apps.zarantonello.dev/namespace: immich
  # Persistent volume cannot be read by 2 replicas.
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        apps.zarantonello.dev/name: redis
        apps.zarantonello.dev/namespace: immich
    spec:
      containers:
        - image: docker.io/library/redis:8.2.2@sha256:f0957bcaa75fd58a9a1847c1f07caf370579196259d69ac07f2e27b5b389b021
          name: redis
          ports:
            - containerPort: 6379
              name: redis
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /data
              name: data
      enableServiceLinks: false
      nodeSelector:
        kubernetes.io/hostname: srv-0-thi-home
      securityContext:
        fsGroup: 6097
        runAsGroup: 6097
        runAsNonRoot: true
        runAsUser: 6097
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: redis-data
