apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      apps.zarantonello.dev/name: redis
      apps.zarantonello.dev/namespace: immich
  # Persistent volume cannot be read by 2 replicas.
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        apps.zarantonello.dev/name: redis
        apps.zarantonello.dev/namespace: immich
    spec:
      containers:
        - image: docker.io/library/redis:8.10.0@sha256:344e3945a0b431c8ff1eecd58c5573538126bd756f02fc7e218ddf1fc2546366
          name: redis
          ports:
            - containerPort: 6379
              name: redis
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /data
              name: data
      enableServiceLinks: false
      nodeSelector:
        kubernetes.io/hostname: srv-home
      securityContext:
        runAsGroup: 6097
        runAsNonRoot: true
        runAsUser: 6097
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: redis-data
