apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
spec:
  selector:
    matchLabels:
      apps.zarantonello.dev/name: vaultwarden
      apps.zarantonello.dev/namespace: vaultwarden
  # Persistent volume cannot be read by 2 replicas.
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        apps.zarantonello.dev/name: vaultwarden
        apps.zarantonello.dev/namespace: vaultwarden
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: vaultwarden-env
            - secretRef:
                name: vaultwarden-env
          image: quay.io/vaultwarden/server:1.37.2@sha256:094b5689ed81549bd293418395c7cf495ae9d960fc2d4928cef2083ef913d912
          name: vaultwarden
          ports:
            - containerPort: 3000
              name: http
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /data
              name: data
      enableServiceLinks: false
      nodeSelector:
        kubernetes.io/hostname: srv-hetz-nbg-0
      securityContext:
        runAsGroup: 53382
        runAsNonRoot: true
        runAsUser: 53382
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
