apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
spec:
  selector:
    matchLabels:
      apps.zarantonello.dev/name: vaultwarden
      apps.zarantonello.dev/namespace: vaultwarden
  # Persistent volume cannot be read by 2 replicas.
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        apps.zarantonello.dev/name: vaultwarden
        apps.zarantonello.dev/namespace: vaultwarden
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: vaultwarden-env
            - secretRef:
                name: vaultwarden-env
          image: quay.io/vaultwarden/server:1.34.3@sha256:84fd8a47f58d79a1ad824c27be0a9492750c0fa5216b35c749863093bfa3c3d7
          name: vaultwarden
          ports:
            - containerPort: 3000
              name: http
          readinessProbe:
            exec:
              command:
                - /healthcheck.sh
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /data
              name: data
      enableServiceLinks: false
      nodeSelector:
        kubernetes.io/hostname: srv-0-cor-home
      securityContext:
        fsGroup: 53382
        runAsGroup: 53382
        runAsNonRoot: true
        runAsUser: 53382
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
