apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: default
spec:
  hostnames:
    - git.zarantonello.dev
  parentRefs:
    - name: srv-hetz-nbg-0-public-https
      namespace: cilium
    - name: srv-hetz-nbg-0-tailscale-https
      namespace: cilium
    - name: srv-hetz-nbg-0-tailscale-http
      namespace: cilium
    - name: srv-hetz-nbg-0-internal-https
      namespace: cilium
    - name: srv-hetz-nbg-0-internal-http
      namespace: cilium
  rules:
    - backendRefs:
        - name: http
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
