apiVersion: v1
kind: Service
metadata:
  name: bittorrent
spec:
  ports:
    - name: bittorrent-tcp
      port: 51413
      protocol: TCP
      targetPort: bittorrent-tcp
    - name: bittorrent-udp
      port: 51413
      protocol: UDP
      targetPort: bittorrent-udp
  selector:
    apps.zarantonello.dev/name: transmission
    apps.zarantonello.dev/namespace: transmission
