apiVersion: v1
kind: Service
metadata:
  name: http-caddy
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    apps.zarantonello.dev/name: caddy
    apps.zarantonello.dev/namespace: transmission
