apiVersion: v1
kind: Service
metadata:
  name: http-transmission
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    apps.zarantonello.dev/name: transmission
    apps.zarantonello.dev/namespace: transmission
