apiVersion: zarantonello.dev/v1
kind: DnsRecord
metadata:
  name: llama-zarantonello-dev
  namespace: immich
spec:
  data:
    - A:
        addresses:
          - 100.107.198.103
    - AAAA:
        addresses:
          - fd7a:115c:a1e0::1836:c668
  fqdn: llama.zarantonello.dev
