apiVersion: zarantonello.dev/v1
kind: DnsRecord
metadata:
  name: vault-zarantonello-net
  namespace: vaultwarden
spec:
  data:
    - A:
        addresses:
          - 100.83.193.88
    - AAAA:
        addresses:
          - fd7a:115c:a1e0::d136:c159
  fqdn: vault.zarantonello.net
