apiVersion: v1
kind: PersistentVolume
metadata:
  name: actual-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  local:
    path: /var/mnt/data-0/actual-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - srv-0-thi-home
