machine:
  install:
    disk: /dev/sda
    image: factory.talos.dev/metal-installer/4a0d65c669d46663f377e7161e50cfd570c401f26fd9e7bda34a0216b6f1922b:v1.11.2
  network:
    hostname: srv-0-nbg-hetz.servers.zarantonello.dev
    interfaces:
      - addresses:
          - 2a01:4f8:1c1a:3498::/64
        # Setting ipv4 and ipv6 gateways leads to only the ipv6 one being kept.
        # I have no idea why, so we just let dhcp handle ipv4.
        dhcp: true
        interface: enp1s0
        routes:
          - gateway: fe80::1
            network: ::/0
      - addresses:
          - 10.95.0.1/24
          - fda9:b00c:8b29:33f9::1095:1/120
        interface: wg0
        mtu: 1400
        wireguard:
          listenPort: 51000
          peers:
            # srv-0-cor-home
            - allowedIPs:
                - 10.95.0.2/32
                - fda9:b00c:8b29:33f9::1095:2/128
              endpoint: srv-0-cor-home.servers.zarantonello.dev:51000
              publicKey: dNUWq6FfG7+3AGl5olQOpVel6Ntl4brufEQOlN9VPEM=
            # srv-0-thi-home (no endpoint due to firewall restrictions)
            - allowedIPs:
                - 10.95.0.3/32
                - fda9:b00c:8b29:33f9::1095:3/128
              publicKey: j5Afx7hXJkjHHmDuzmScMrjL3oWpZxT6WL6xMIX87H0=
          privateKey: ENC[AES256_GCM,data:e1g7qiKjGJTHMbvh5nR47E+jy5A9EtLECf6o98QVCATUCNH19etne6e9+Zw=,iv:TMqtKLybxHGKsrtW913wEFaSksaPraBXVwb5WbbPY+c=,tag:hOD0vNYLC19vsjQwqLQtCw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLN1QwRzNROExrTGt6VUxp
        cjZaOW4yRERqcXJ5bkJRUFN0YVBmNkZHMmc4Cnk2ekk1OU5YRzN2QkNxVU5mYnMy
        SXJzcHo5M2RlR29VMkhvbkhONW9KaFUKLS0tIDB6eUs3Wk5UbkNYMDdiTUdLOXpu
        TGZSWnVGb3NKSHpIak5YTFdramR6ZHMKZFGJOLBLD0bzuzh2lLpGXlAzvj0mMO6r
        Upbq5PVuT/EzJMZOIxRYsvTMkcs8Z+Du3kd2j0GV4LRARll3lUZzYg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10s8xudjc20ujqjsk0asex5vgxqtm3fzrx2g3lzt5lls4rsay6cpqx6rhcc
  encrypted_regex: privateKey
  lastmodified: "2025-09-29T07:59:24Z"
  mac: ENC[AES256_GCM,data:odpGbU3B4tKimQAdMQm9QE/K8P+L8l0A8ffSmhhjHNmGznY76ct8V5k1MEsv7L8j3thZ8hNHeRDnVczX/IWmQ4AObyOIkhkxatDOilOVrpjcCgiWVCy/YDSrPqTYbr2/cG1AyD0Nkbpza8R+stRSNSSWAOJzD2ZFaxwhLHm8f/8=,iv:b+tMxMTv2T2g4DtENsTT6yR187z68ERq4IveKw2YJQg=,tag:kgstNxruFzgFsH3Y7fOZDA==,type:str]
  version: 3.10.2
