apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      apps.zarantonello.dev/name: server
      apps.zarantonello.dev/namespace: umami
  template:
    metadata:
      labels:
        apps.zarantonello.dev/name: server
        apps.zarantonello.dev/namespace: umami
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres.umami.svc.k8s.zarantonello.dev:5432/$(POSTGRES_DB)
          envFrom:
            - secretRef:
                name: postgres-env
            - configMapRef:
                name: server-env
          image: ghcr.io/umami-software/umami:3.3.0@sha256:87312d334d009ee67ee0d2fba8fed01435547cc468e452243aef5133a9984d48
          name: umami
          ports:
            - containerPort: 3000
              name: http
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      enableServiceLinks: false
      nodeSelector:
        kubernetes.io/hostname: srv-hetz-nbg-0
      securityContext:
        runAsGroup: 1393
        runAsNonRoot: true
        runAsUser: 1393
        seccompProfile:
          type: RuntimeDefault
